# Generated by Django 4.2.2 on 2023-06-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_bookcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Author"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created"], "verbose_name_plural": "Book"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
        migrations.AddField(
            model_name="book",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("A", "Advance"), ("I", "Intermediate"), ("B", "Basic")],
                max_length=5,
                null=True,
            ),
        ),
    ]
