# Generated by Django 4.2.2 on 2023-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="upload"),
        ),
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("B", "Basic"), ("A", "Advance"), ("I", "Intermediate")],
                max_length=5,
                null=True,
            ),
        ),
    ]
